name: Trigger Inputs Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment Target Environment'
        options:
          - dev
          - uat
        required: true
        default: 'dev'    

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      ## print the branch name
      - name: Print Branch Name
        run: echo "Branch: ${{ github.ref_name }}"
      - name: Print Event Name
        run: echo "Event: ${{ github.event_name }}"
      - name: Print Inputs
        if: github.event_name == 'workflow_dispatch'
        run: echo "Inputs: ${{ toJson(github.event.inputs) }}"  

    outputs:
      ## Set the main branch default environment to uat and dev for other branches, 
      ## optionally, if triggered by dispatch, set the environment based on the input
      deploy_env: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' && inputs.env || 'uat') || 'dev' }}

  echo:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Branch Name and Environment
        run: |
          echo "Deployment Branch: ${{ github.ref_name }}"
          echo "Deployment Environment: ${{ needs.init.outputs.deploy_env }}"