name: Trigger Inputs Environment

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Deployment Target Environment'
        options:
          - dev
          - uat
        required: true
        default: dev

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Branch Name
        run: echo "Deployment Branch is ${{ github.ref_name }}"
      - name: Print Inputs
        if: github.event_name == 'workflow_dispatch'
        run:  echo "Input Environment is ${{ inputs.env }}"
    outputs:
      ## Set the main branch default environment to uat and dev for other branches, 
      ## optionally, if triggered by dispatch, set the environment based on the input
      deploy_env: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' && inputs.env || 'uat') || 'dev' }}

  deploy:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Branch Name and Environment
        run: |
          echo "Deployment Branch: ${{ github.ref_name }}"
          echo "Deployment Environment: ${{ needs.init.outputs.deploy_env }}"