name: Trigger Inputs Environment

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment Target Environment'
        options:
          - dev
          - uat
        required: true
        default: 'dev'    

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Initialization step for environment ${{ inputs.env }}"
    outputs:
      ## Set the main branch default environment to uat and dev for other branches, 
      ## optionally, if triggered by dispatch, set the environment based on the input
      deploy_env: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' && inputs.env || 'uat') || 'dev' }}

  echo:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "Input Environment is ${{ github.event.inputs.env }}"
      - name: Echo Deploy Environment
        run: echo "Deployment Target Environment is ${{ needs.init.outputs.deploy_env }}"  